steps:
  - id: 'decrypt secrets'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ './scripts/decrypt_secrets.sh', '-e=${_TARGET_ENVIRONMENT}' ]
  - id: 'fetch perm key'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'secrets'
      - 'versions'
      - 'access'
      - 'latest'
      - '--secret'
      - 'potw-gcloud-builder-perm-key'
      - '--out-file'
      - '/tmp/gcloud-perm-key.json'
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'ENV_FILE=$_TARGET_ENVIRONMENT',
      '-t',
      'gcr.io/$PROJECT_ID/quirkles-potw:$COMMIT_SHA',
      '.'
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quirkles-potw:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quirkles-potw'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quirkles-potw:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/quirkles-potw:$COMMIT_SHA'