import type { Metadata } from "next";
import { Overpass_Mono } from "next/font/google";
import "./styles/globals.css";
import "./styles/reset.css";

const overpassMono = Overpass_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={overpassMono.className}>{children}</body>
    </html>
  );
}
